workflows:
  go_ttc_ios:
    name: GO TTC iOS build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        # You can change this later in Xcode / Info.plist if needed
        BUNDLE_ID: "com.shivank.goTtcBoard"

    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/**/*.xcarchive
      - flutter_drive.log

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
